# Generated by Django 5.2 on 2025-05-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_feeding"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feeding",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="feeding",
            name="date",
            field=models.DateField(verbose_name="Feeding Date"),
        ),
    ]
